Programm started at: 2025-07-28 02:02:33

Running in version 1.2[2025-07-28 23:32:09]
Git repositories synchronized
	

	NoneType: None


[2025-07-28 23:32:09]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-29 02:01:56

Running in version 1.2

[2025-07-29 23:32:33]
Git repositories synchronized
	

	NoneType: None


[2025-07-29 23:32:33]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-30 02:02:58

Running in version 1.2

[2025-07-30 23:32:34]
Git repositories synchronized
	

	NoneType: None


[2025-07-30 23:32:34]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-31 02:02:45

Running in version 1.2

[2025-07-31 23:32:19]
Git repositories synchronized
	

	NoneType: None


[2025-07-31 23:32:19]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-08-01 02:02:18

Running in version 1.2

[2025-08-01 23:32:51]
Git repositories synchronized
	

	NoneType: None


[2025-08-01 23:32:51]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-08-02 02:03:00

Running in version 1.2

[2025-08-02 04:23:04]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


[2025-08-02 23:32:36]
Git repositories synchronized
	

	NoneType: None


[2025-08-02 23:32:36]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-08-03 02:02:28

Running in version 1.2

[2025-08-03 07:35:35]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


[2025-08-03 23:33:08]
Git repositories synchronized
	

	NoneType: None


[2025-08-03 23:33:08]
Terminating programm
	

	NoneType: None


