Programm started at: 2025-06-16 10:04:39

Running in version 1.2New initialisation demanded at: 2025-06-16 10:43:40

Running in version 1.2

New initialisation demanded at: 2025-06-16 10:57:32

Running in version 1.2

[2025-06-16 23:42:52]
Git repositories synchronized
	

	NoneType: None


[2025-06-16 23:42:52]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-17 01:48:18

Running in version 1.2

[2025-06-17 14:14:35]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


[2025-06-17 17:07:40]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


[2025-06-17 23:42:54]
Git repositories synchronized
	

	NoneType: None


[2025-06-17 23:42:54]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-18 01:47:51

Running in version 1.2

[2025-06-18 23:42:25]
Git repositories synchronized
	

	NoneType: None


[2025-06-18 23:42:25]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-19 01:48:49

Running in version 1.2

[2025-06-19 10:09:01]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


[2025-06-19 23:42:25]
Git repositories synchronized
	

	NoneType: None


[2025-06-19 23:42:25]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-20 01:48:47

Running in version 1.2

[2025-06-20 23:42:22]
Git repositories synchronized
	

	NoneType: None


[2025-06-20 23:42:22]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-21 01:48:28

Running in version 1.2

[2025-06-21 23:42:03]
Git repositories synchronized
	

	NoneType: None


[2025-06-21 23:42:03]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-06-22 01:48:57

Running in version 1.2

[2025-06-22 04:45:02]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


[2025-06-22 14:41:18]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


