Programm started at: 2025-09-22 02:02:47

Running in version 1.2[2025-09-22 23:32:20]
Git repositories synchronized
	

	NoneType: None


[2025-09-22 23:32:20]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-23 02:02:44

Running in version 1.2

[2025-09-23 23:32:18]
Git repositories synchronized
	

	NoneType: None


[2025-09-23 23:32:18]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-24 02:02:04

Running in version 1.2

[2025-09-24 23:32:38]
Git repositories synchronized
	

	NoneType: None


[2025-09-24 23:32:38]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-25 02:03:09

Running in version 1.2

[2025-09-25 23:32:43]
Git repositories synchronized
	

	NoneType: None


[2025-09-25 23:32:43]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-26 02:03:01

Running in version 1.2

[2025-09-26 23:32:35]
Git repositories synchronized
	

	NoneType: None


[2025-09-26 23:32:35]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-27 02:02:23

Running in version 1.2

[2025-09-27 23:32:57]
Git repositories synchronized
	

	NoneType: None


[2025-09-27 23:32:57]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-28 02:03:24

Running in version 1.2

[2025-09-28 22:16:53]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


