Programm started at: 2025-09-15 02:02:03

Running in version 1.2[2025-09-15 23:32:37]
Git repositories synchronized
	

	NoneType: None


[2025-09-15 23:32:37]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-16 02:03:06

Running in version 1.2

[2025-09-16 23:32:41]
Git repositories synchronized
	

	NoneType: None


[2025-09-16 23:32:41]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-17 02:02:52

Running in version 1.2

[2025-09-17 20:38:18]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


[2025-09-17 23:32:27]
Git repositories synchronized
	

	NoneType: None


[2025-09-17 23:32:27]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-18 02:01:59

Running in version 1.2

New initialisation demanded at: 2025-09-18 18:50:40

Running in version 1.2

[2025-09-18 23:32:50]
Git repositories synchronized
	

	NoneType: None


[2025-09-18 23:32:50]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-19 02:02:53

Running in version 1.2

[2025-09-19 14:17:11]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


[2025-09-19 21:09:21]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


[2025-09-19 23:32:30]
Git repositories synchronized
	

	NoneType: None


[2025-09-19 23:32:30]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-20 02:02:35

Running in version 1.2

[2025-09-20 08:32:43]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


