Programm started at: 2025-07-07 02:28:34

Running in version 1.2[2025-07-07 23:32:16]
Git repositories synchronized
	

	NoneType: None


[2025-07-07 23:32:16]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-08 02:28:11

Running in version 1.2

[2025-07-08 23:32:54]
Git repositories synchronized
	

	NoneType: None


[2025-07-08 23:32:54]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-09 02:27:57

Running in version 1.2

[2025-07-09 23:32:40]
Git repositories synchronized
	

	NoneType: None


[2025-07-09 23:32:40]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-10 02:28:30

Running in version 1.2

[2025-07-10 23:32:12]
Git repositories synchronized
	

	NoneType: None


[2025-07-10 23:32:12]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-11 02:28:13

Running in version 1.2

New initialisation demanded at: 2025-07-11 13:33:52

Running in version 1.2

[2025-07-11 23:32:12]
Git repositories synchronized
	

	NoneType: None


[2025-07-11 23:32:12]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-12 02:01:38

Running in version 1.2

[2025-07-12 23:32:14]
Git repositories synchronized
	

	NoneType: None


[2025-07-12 23:32:14]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-13 02:01:27

Running in version 1.2

[2025-07-13 18:10:51]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


[2025-07-13 23:32:04]
Git repositories synchronized
	

	NoneType: None


[2025-07-13 23:32:04]
Terminating programm
	

	NoneType: None


