Programm started at: 2025-09-01 01:31:03

Running in version 1.2[2025-09-01 23:31:38]
Git repositories synchronized
	

	NoneType: None


[2025-09-01 23:31:38]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-02 01:31:51

Running in version 1.2

[2025-09-02 23:31:25]
Git repositories synchronized
	

	NoneType: None


[2025-09-02 23:31:25]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-03 01:31:21

Running in version 1.2

[2025-09-03 23:31:56]
Git repositories synchronized
	

	NoneType: None


[2025-09-03 23:31:56]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-04 01:30:54

Running in version 1.2

[2025-09-04 23:31:30]
Git repositories synchronized
	

	NoneType: None


[2025-09-04 23:31:30]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-05 01:31:37

Running in version 1.2

[2025-09-05 19:20:02]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


[2025-09-05 23:31:13]
Git repositories synchronized
	

	NoneType: None


[2025-09-05 23:31:13]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-06 01:31:24

Running in version 1.2

[2025-09-06 23:32:00]
Git repositories synchronized
	

	NoneType: None


[2025-09-06 23:32:00]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-09-07 01:31:02

Running in version 1.2

[2025-09-07 12:59:18]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


[2025-09-07 23:31:39]
Git repositories synchronized
	

	NoneType: None


[2025-09-07 23:31:39]
Terminating programm
	

	NoneType: None


