Programm started at: 2025-07-21 01:31:17

Running in version 1.2[2025-07-21 23:31:54]
Git repositories synchronized
	

	NoneType: None


[2025-07-21 23:31:54]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-22 01:32:02

Running in version 1.2

[2025-07-22 18:36:27]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


[2025-07-22 23:31:40]
Git repositories synchronized
	

	NoneType: None


[2025-07-22 23:31:40]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-23 01:31:52

Running in version 1.2

[2025-07-23 23:31:29]
Git repositories synchronized
	

	NoneType: None


[2025-07-23 23:31:29]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-24 01:31:34

Running in version 1.2

[2025-07-24 08:36:44]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


[2025-07-24 19:51:02]
Error 1 at reading or storing sensor data.
	'I2C read failed'

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 191, in read_all
    if self.data_available():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 172, in data_available
    value = self.pi.i2c_read_byte_data(self.device, CSS811_STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 2874, in i2c_read_byte_data
    return _u2i(_pigpio_command(self.sl, _PI_CMD_I2CRB, handle, reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C read failed'


[2025-07-24 23:31:13]
Git repositories synchronized
	

	NoneType: None


[2025-07-24 23:31:13]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-25 01:32:11

Running in version 1.2

[2025-07-25 23:31:49]
Git repositories synchronized
	

	NoneType: None


[2025-07-25 23:31:49]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-26 01:31:50

Running in version 1.2

[2025-07-26 23:31:27]
Git repositories synchronized
	

	NoneType: None


[2025-07-26 23:31:27]
Terminating programm
	

	NoneType: None


New initialisation demanded at: 2025-07-27 01:31:25

Running in version 1.2

[2025-07-27 02:07:26]
Error 1 at reading or storing sensor data.
	I2C read failed

	Traceback (most recent call last):
  File "/home/raspi/CO2_Project/main.py", line 211, in <module>
    g_co2_sensor.read_all()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 192, in read_all
    self.read_logorithm_results()
  File "/home/raspi/CO2_Project/ccs811LIBRARY.py", line 188, in read_logorithm_results
    raise Exception (pigpio.error_text(b))
Exception: I2C read failed


[2025-07-27 23:32:03]
Git repositories synchronized
	

	NoneType: None


[2025-07-27 23:32:03]
Terminating programm
	

	NoneType: None


